# Generated by Django 5.2.8 on 2025-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='author',
            field=models.IntegerField(),
        ),
    ]
